### ISSUE TITLE
Some (possibly all) car files don't contain program id index for inner instructions

### ISSUE THREAD

**Issue by ring0-rootkit** [rpcpool/yellowstone-faithful#138]
So, I stumbled upon an issue where inner instructions in  all epochs that i've checked (626, 624, 623) don't have programIdIndex, here is what I get when I parse transactions from car files:
```
tx signature: 4MZUsuccxz2EWzJDZ547VqvDYuESpM9cbRpn6uYMNK93JuTPUTx3hSZdq4xBkMJ8nHAfQStPaeRDEFFhepjXNevk
inner instruction index: 4
outer instruction index: 9
program id index: 0
account keys: [EiAq1CALGJ4NjUej6GTGNswiZCyGefGwsXcYbk5AKZ25 7bBaVBMVHjZ5Ydf89JugQCoiYL6RFg2QSgVFLJiMaZTB 937UNuzvqiLdopRaRb1Wka5Hrct2uniKmi61xoMVUHC4 CsVZsc37H5rWznBuy7VpvJePvFV157yU11iYNGN7dtza CkeQKW6NxMV3cnMSRrvG31pNWjxx9FScUbA9dpYeVAyb Ddw7tY2i9U5S38EKU2soQBu8jBGKUVkFR5DPApxS8YrW DbK9zkkFDh9aHfV3TVbbDjrXtFtdecSbsGwfofW4KzvC GPTRveZEaAV7m2VjeYSjaLaoubgF7Lyc27L6EGhK5VrN 7hRuuZirTnqpchVuU6jkMrRYK6YdnSyr8oHkp6QZPR2B GHRaHag4bAFmFkQvK8DQeo1jF1JBguhWFa8Udi5fX8ED HNU2PPKQYVYgi8zkQJG7bep3mEXJWvcJeJwPVmfi8Z3u EQVQ11GvXZuE2xEqVdjhMvFPFvQLBb8EuQvGNZWTb7y9 BtgJkrqvE53jHHqw2DckL1697raPEXSCuMZGZCVo3ASw APBRxoEErDuHWF5STBhy2yDE472xyJXkGVRpcLWGHKjf ComputeBudget111111111111111111111111111111 3tZPEagumHvtgBhivFJCmhV9AyhBHGW9VgdsK52i4gwP 11111111111111111111111111111111 JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX DoyfsKStMN2xdqt6nYQtoGqPJzcJZ88ASFuyHZAPioy1]
```
I can provide more examples if needed

For reference:
To get transaction I use FindTransactions method
To parse Transaction I use: parseTransactionAndMetaFromNode method from storage.go:174
To parse metadata I use: encodeTransactionResponseBasedOnWantedEncoding

**Comment by ring0-rootkit** [comment]
UPDATE: checked all epochs I had, results:
missing programid in epochs: 626 - 617, 632
This is every epochs I have, unfortunately :(

**Comment by gagliardetto** [comment]
there might be some bug in `encodeTransactionResponseBasedOnWantedEncoding`

You're better off just doing `tx, meta, err := parseTransactionAndMetaFromNode(transactionNode, epochHandler.GetDataFrameByCid)` and then asserting `txMeta := meta.(*confirmed_block.TransactionStatusMeta)` (all modern epochs use that format).

**Comment by ring0-rootkit** [comment]
Ok and what about old epochs?

**Comment by gagliardetto** [comment]
It's gonna be one of these:

https://github.com/rpcpool/yellowstone-faithful/blob/bcfb24a14f6cee5c8df5c45b102b5ec4c71107e9/solana-tx-meta-parsers/parsers.go#L39

**Comment by gagliardetto** [comment]
You just need to make a switch statement on the type of meta.

**Comment by ring0-rootkit** [comment]
Ok, thank you I'll try it out

**Comment by ring0-rootkit** [comment]
Ok, so I checked and it is skill issue, I mean programIdIndex is actually absent but as it should, and programId is returned already parsed for me. So there is no bug, thank you for your time
