### ISSUE TITLE
Broken link for hosted archive

### ISSUE THREAD

**Issue by iondex** [rpcpool/yellowstone-faithful#156]
Hi! Thank you for your great work to archive Solana historical data. However, it seems that the hosted archive link ( https://files.old-faithful.net/ ) is broken. Is there a hosted copy that can be retrieved, or it is required to download the copy elsewhere?

**Comment by Lusitaniae** [comment]
What file are you trying to pull?

It could be missing the latest few epochs

**Comment by iondex** [comment]
Sorry for the reply. I was trying to figure out the directory and file structure, and it constantly returns 404. After the update of the docs, I can now retrieve the car files. Thank you! Will close this issue.
