### ISSUE TITLE
Create a function to read and sort a list of urls of car splits / validate car file splits

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#169]
1. HEAD request to get size
2. Read header
3. Figure out CID for subset
4. Read a chunk at the end to load the subset

This will give us:
- start and end slot
- plus ordering
- validation that the remote car file is what we expect
- validation that we have all the slots for the epoch 

This can also be done when loading split car files from the file system so we can validate that we have every slot in the epoch.

**Comment by anjor** [comment]
@linuskendall just to confirm this is basically a url version of https://github.com/rpcpool/yellowstone-faithful/pull/166  right?

**Comment by linuskendall** [comment]
Yep!

**Comment by anjor** [comment]
This is now done.
