### ISSUE TITLE
Support geyser plugins

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#22]
Can we support geyser plugins? 

Either:
- have rust car reader / dump call in golang
- have faithful-cli support geyser plugins
- implement a small shim faithful-cli -> socket -> rust geyser plugin manager / loader
- support rust via a golang shim reading the car file

**Comment by linuskendall** [comment]
- BlockMeta
- Transaction
- Slot

following the geyser interface callbacks: https://github.com/solana-labs/solana/blob/master/geyser-plugin-interface/src/geyser_plugin_interface.rs

**Comment by gagliardetto** [comment]
```
update_slot_status
notify_transaction
notify_block_metadata
```

**Comment by gagliardetto** [comment]
implemented
