### ISSUE TITLE
Transparent proxy mode

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#29]
One of the requests we got was a mode where the proxy would forward any requests it didnt recognise (ie. any rpc calls it couldnt handle) to an upstream endpoint. This would simplify the deployment scenarios for some as they could just place faithful (handling getTxn, getSFA, getBlock) in front of a solana validator forwarding any ohter calls straight to the validator.

**Comment by gagliardetto** [comment]
And the proxy config would be a file?

With a url and maybe headers.
