### ISSUE TITLE
Fix epochs that have extra blocks 

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#73]
For some epochs the 'last block detection' didn't work, which the PoH validation showed. We need to regenerate these epochs and re-upload them with the corrected last epoch.

**Comment by linuskendall** [comment]
@gagliardetto to add some details on how we will do this with radiance so that it knows where to stop.

**Comment by gagliardetto** [comment]
In https://github.com/gagliardetto/radiance-triton I added a `--stop-at-slot=999999999` flag (inclusive) that cuts the excess blocks from epochs that have them (you need to know the slot you need).
