### ISSUE TITLE
Add prometheus metrics to faithful rpc

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#82]
- Epochs available `epoch_available{epoch="200"} = 1`
- RPC requests by method (counter)
- .. ?

**Comment by Lusitaniae** [comment]
status_code, miner ids, source type (ipfs/bitwarden/s3/etc)

response time histogram

**Comment by gagliardetto** [comment]
I added a few metrics to https://github.com/rpcpool/yellowstone-faithful/pull/86

> miner ids

Like just a list of miner IDs that have one or more pieces?

> source type

How should that be split up?

**Comment by gagliardetto** [comment]
completed in https://github.com/rpcpool/yellowstone-faithful/pull/86
